<?php
/**
 * RoundCube Calendar
 *
 * Plugin to add a calendar to RoundCube.
 *
 * @version 0.2 BETA 2
 * @author Lazlo Westerhof
 * @url http://rc-calendar.lazlo.me
 * @licence GNU GPL
 * @copyright (c) 2010 Lazlo Westerhof - Netherlands
 *
 **/

$labels = array();

// config
$labels['24_hour'] = 'Verwende 24 Stunden Format';
$labels['timeslots'] = 'Anzahl Unterteilungen pro Stunde';
$labels['first_day'] = 'Erster Tag der Woche';

// calendar
$labels['calendar'] = 'Kalender';
$labels['day'] = 'Tag';
$labels['week'] = 'Woche';
$labels['month'] = 'Monat';
$labels['new_event'] = 'Neuer Kalendereintrag';
$labels['edit_event'] = 'Kalendereintrag editieren';
$labels['save'] = 'Speichern';
$labels['remove'] = 'Löschen';
$labels['cancel'] = 'Abbrechen';
?>